// Generated by gencpp from file iturov/bottom.msg
// DO NOT EDIT!


#ifndef ITUROV_MESSAGE_BOTTOM_H
#define ITUROV_MESSAGE_BOTTOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace iturov
{
template <class ContainerAllocator>
struct bottom_
{
  typedef bottom_<ContainerAllocator> Type;

  bottom_()
    : dec_16()  {
    }
  bottom_(const ContainerAllocator& _alloc)
    : dec_16(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _dec_16_type;
  _dec_16_type dec_16;





  typedef boost::shared_ptr< ::iturov::bottom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::iturov::bottom_<ContainerAllocator> const> ConstPtr;

}; // struct bottom_

typedef ::iturov::bottom_<std::allocator<void> > bottom;

typedef boost::shared_ptr< ::iturov::bottom > bottomPtr;
typedef boost::shared_ptr< ::iturov::bottom const> bottomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::iturov::bottom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::iturov::bottom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::iturov::bottom_<ContainerAllocator1> & lhs, const ::iturov::bottom_<ContainerAllocator2> & rhs)
{
  return lhs.dec_16 == rhs.dec_16;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::iturov::bottom_<ContainerAllocator1> & lhs, const ::iturov::bottom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace iturov

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::iturov::bottom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::iturov::bottom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iturov::bottom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::iturov::bottom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iturov::bottom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::iturov::bottom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::iturov::bottom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a569087f646e4f1ea9df66c6efd925f2";
  }

  static const char* value(const ::iturov::bottom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa569087f646e4f1eULL;
  static const uint64_t static_value2 = 0xa9df66c6efd925f2ULL;
};

template<class ContainerAllocator>
struct DataType< ::iturov::bottom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "iturov/bottom";
  }

  static const char* value(const ::iturov::bottom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::iturov::bottom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string dec_16\n"
;
  }

  static const char* value(const ::iturov::bottom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::iturov::bottom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dec_16);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bottom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::iturov::bottom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::iturov::bottom_<ContainerAllocator>& v)
  {
    s << indent << "dec_16: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.dec_16);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITUROV_MESSAGE_BOTTOM_H
